---
nginx_vars:
  package:      'nginx'
  service:      'nginx'
  conf_dir:     '/etc/nginx'
  ca_certs:     '/etc/ssl/cert.pem'
  pid_path:     '/run/nginx.pid'
  log_dir:      '/var/log/nginx'
  owner:        'nginx'
  group:        'nginx'
  root_owner:   'root'
  root_group:   'root'
  event_notify: 'auto'
